// FinalTestReact/src/App.jsx
import './App.css'
import Nav from './components/Nav';
import Footer from './components/Footer';
import Section1 from './components/Section1';
import Section2 from './components/Section2';
import Section3 from './components/Section3';

function App() {

  return (
    <>

      <Nav />

      <Section1 />

      <Section2 />

      <Section3 />

      <Footer />

    </>
  )
}

export default App

// FinalTestVue/src/App.vue
<script setup>
// import { ref, reactive } from 'vue'
import Nav from './components/Nav.vue';
import Header from './components/Header.vue';
import Section2 from './components/Section2.vue';
import Section3 from './components/Section3.vue';
import Footer from './components/Footer.vue';
</script>

<template>

  <Nav />

  <Header />

  <Section2 />
  
  <Section3 />

  <Footer />

</template>
